name: CI

on:
  push:
    branches:
      - main

jobs:
  run-terraform:
    name: 'Run Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5.0.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.0
        with:
          role-to-assume: ${{ secrets.AWS_TERRAFORM_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.0

      - name: Run terraform init
        run: terraform init

      - name: Run terraform format
        run: terraform fmt -check

      - name: Run terraform validate
        run: terraform validate

      - name: Run terraform plan
        run: terraform plan

      - name: Run terraform apply
        run: terraform apply -auto-approve
